export const AFEGIR_PRODUCTE = 'AFEGIR_PRODUCTE';
export const AFEGIR_PRODUCTE_EXIT = 'AFEGIR_PRODUCTE_EXIT';
export const AFEGIR_PRODUCTE_ERROR = 'AFEGIR_PRODUCTE_ERROR';

export const INICIAR_DESCARREGA_ITEMS = 'INICIAR_DESCARREGA_ITEMS';
export const DESCARREGA_ITEMS_EXIT = 'DESCARREGA_ITEMS_EXIT';
export const DESCARREGA_ITEMS_ERROR = 'DESCARREGA_ITEMS_ERROR';

export const OBTENIR_PRODUCTE_ELIMINAR = 'OBTENIR_PRODUCTE_ELIMINAR';
export const PRODUCTE_ELIMINAT_EXIT = 'PRODUCTE_ELIMINAT_EXIT';
export const PRODUCTE_ELIMINAT_ERROR = 'PRODUCTE_ELIMINAT_ERROR';

export const OBTENIR_PRODUCTE_EDITAR = 'OBTENIR_PRODUCTE_EDITAR';
export const INICIAR_EDICIO_PRODUCTE = 'INICIAR_EDICIO_PRODUCTE';
export const PRODUCTE_EDITAT_EXIT = 'PRODUCTE_EDITAT_EXIT';
export const PRODUCTE_EDITAT_ERROR = 'PRODUCTE_EDITAT_ERROR';

export const MOSTRAR_ALERTA = 'MOSTRAR_LAERTA';
export const AMAGAR_ALERTA = 'AMAGAR_LAERTA';
